### ISSUE TITLE
Possible issue in Copyright line in LICENSE

### ISSUE THREAD

**Issue by sidkshatriya** [jmorag/kakoune.el#10]
https://github.com/jmorag/kakoune.el/blob/c39f278811945dbf0958ca8cf81d7b03c39efbcf/LICENSE#L1-L7

I think you may have used the text of another project's MIT license without changing the Copyright line.

Currently it is `Copyright (c) 2010-2018 Google, Inc. http://angularjs.org` which seems wrong

**Comment by jmorag** [comment]
Thanks for catching this! Fixed
